### ISSUE TITLE
要求更新\server\package.json

### ISSUE THREAD

**Issue by haua** [mani95lisa/PomeloFlashDemo#1]
里面的
"pomelo": "~0.6.4",
请改为
"pomelo": "1.0.4",
否则加载模块失败...

**Comment by mani95lisa** [comment]
@haua 多谢提醒，呵呵，一直就没更新过，如果还有其他改动你可以pr一下哈~

**Comment by haua** [comment]
@mani95lisa 哈哈，因为我是菜鸟...连nodejs也是才开始学，想拿个demo来学习，所以这个当初弄了很久的说...然后怕有别的新手也来学可能不会弄，所以稍微提醒一下哈

**Comment by mani95lisa** [comment]
@haua 加油哈，按理说不更新模块也可以正常使用的，最近也没时间看，有问题可以再沟通哈~
